///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class ImgAssets {
  static const String iconsLogoWithoutText =
      'assets/icons/Logo-without-text.png';
  static const String imagesCheck = 'assets/images/check.png';
  static const String imagesClose = 'assets/images/close.png';
  static const String imagesDone = 'assets/images/done.png';
  static const String imagesEmail = 'assets/images/email.png';
  static const String imagesGallery = 'assets/images/gallery.png';

  static const String imagesLightMode = 'assets/images/light-mode.png';

  static const String splashCar = 'assets/images/splash_car.png';
  static const String jzlLogo = 'assets/images/app_logo.png';
  static const String imagesLogoAr = 'assets/images/logo.jpg';
  static const String imagesLogoEn = 'assets/images/logo.jpg';

  static const String imagesNightMode = 'assets/images/night-mode.png';
  static const String imagesNoData = 'assets/images/noData.png';
  static const String imagesSuccessAlert = 'assets/images/successAlert.png';
  static const String done = 'assets/images/done_order.png';
  static const String imagesUser = 'assets/images/user.png';
  static const String imagesWarning = 'assets/images/warning.png';

  static const String orderCompleted = 'assets/images/order_completed.png';
  static const String uploadImage = 'assets/images/upload.png';

  //Amr-----------------------------------------
  static const String sudiaFlagImage = 'assets/images/El_Sudia.png';
  static const String usaFlagImage = 'assets/images/Usa_Flag.png';
  static const String kindUserBackGroundImage =
      'assets/images/kind_user_background.png';
  static const String userImage = 'assets/images/user_image.png';
  static const String deliveryImage = 'assets/images/Delivery_image.png';
  static const String wacherCleaningImage = 'assets/images/cleaner_image.jpeg';
  static const String loginLogoImage = 'assets/images/login_logo_image.png';
  static const String loginBorderImage = 'assets/images/login_border_image.png';
  static const String otpEditPenSvg = 'assets/icons/otp_edit_pen.svg';

  static const String orderCheckDone = 'assets/images/check_done_order.png';
  static const String cancelIcon = 'assets/images/close_icon.png';
}
